Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.4
Creation-Date: 2017-02-06T19:26:55+08:00

====== Makefile ======
Created 星期一 06 二月 2017
	1. 一个规则 ：  
				目标：依赖
						（tab缩进）命令
	2. 两个函数
						$(函数名 函数参数)：

		src = $(wildcard ./src/*.c)  	获取指定目录下的 .c ， 组成一个文件名列表  src = server.c client1.c
		obj = $(patsubst %.c, %.o , $(src))	将第三次个参数中，含有第一个参数的部分，替换第二个参数。obj = server client1
	3. 三个自动变量
		$@	: 在规则中的命令中， 表示目标
		
		$^	： 在规则中的命令中，表示全部依赖

		$<	： 在规则中的命令中，表示第一个依赖。对于模式规则，如果依赖是一个列表，该变量会自动将列表中的值依次取出。

					all: 指代 makefile 最终生成目标。
		
			静态模式规则：
		
				指定死。某个变量对应的值，应该使用哪个模式规则来套用。
